### ISSUE TITLE
请问可以提供一些项目的历史监控数据么

### ISSUE THREAD

**Issue by mcf20** [LinShunKang/MyPerf4J#104]
**问题描述**

请清晰和简洁的描述你遇见的 问题

**运行环境**
* MyPerf4J 版本号，例如，2.8.0、2.9.0 等
* JDK 版本号，例如，JDK7、JDK8 等 
* 运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
* 操作系统，例如，Linux、MacOS、Windows 等

**JVM启动参数** 
```
请把你的JVM启动参数完整的复制出来
```

**配置文件** 
```
请把你的配置文件内容完整的复制出来
```

**异常堆栈** 
```
请把程序的错误栈信息完整的复制出来
```

**Comment by LinShunKang** [comment]
你要这个数据做什么？

**Comment by mcf20** [comment]
准备将其建模为序列图结构，使用图神经网络对项目性能瓶颈做一个预测把
&nbsp;


文少i
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月25日(星期二) 上午8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LinShunKang/MyPerf4J] 请问可以提供一些项目的历史监控数据么 (Issue #104)














 
你要这个数据做什么？

**Comment by LinShunKang** [comment]
我不能把公司内部项目的指标给你，但你可以找一个项目接入 MyPerf4J 之后进行压测，这样就能拿到监控指标了。
