### ISSUE TITLE
适配及使用咨询

### ISSUE THREAD

**Issue by IcedOranges** [LinShunKang/MyPerf4J#105]
请问MyPerf4J是否支持
1. Springboot3.3+jdk21的项目
2. Docker-compose在linux（Ubuntu 或 CentOS）下直接部署

**Comment by LinShunKang** [comment]
你好，目前 [feature/support_springboot3](https://github.com/LinShunKang/MyPerf4J/tree/feature/support_springboot3) 分支支持 SpringBoot3

**Comment by LinShunKang** [comment]
1. 最新的 v3.4.0 已支持 SpringBoot3，切换至 master 分支即可下载。
2. MyPerf4J 是 Java Agent 只要是非 Native 的应用都能支持。
