### ISSUE TITLE
参数加到jvm启动参数中服务启动不了

### ISSUE THREAD

**Issue by zmr518** [LinShunKang/MyPerf4J#21]
参数加到jvm启动参数中启动不了，求解
export JAVA_OPTS=“-javaagent:/tmp/MyPerf4J/MyPerf4J-ASM.jar -DMyPerf4JPropFile=/tmp/MyPerf4J/myPerf4J.properties”

**Comment by bergger** [comment]
我的问题是程序正常执行，但没有输出metrics日志

1、测试类：
`package demo;

public class TestMyPerf {
    public static void main(String[] args) throws InterruptedException {
        for (int i=0; i<10000;i++) {
            test();
        }
    }

    public static void test() throws InterruptedException {
        Thread.sleep((int)(Math.random() * 300));
        System.out.println(System.currentTimeMillis() + " test");
    }
}`

2、编译   javac demo/TestMyPerf.java

3、执行   java demo/TestMyPerf -DMyPerf4JPropFile=/Users/abc/git/MyPerf4J/myPerf4J.properties -javaagent:/Users/abc/git/MyPerf4J/MyPerf4J-ASM-2.1.0.jar

4、配置文件
AppName=MyPerf4JTest
MetricsProcessorType=1
MethodMetricsFile=/data/logs/MyPerf4J/method_metrics.log
ClassMetricsFile=/data/logs/MyPerf4J/class_metrics.log
GCMetricsFile=/data/logs/MyPerf4J/gc_metrics.log
MemMetricsFile=/data/logs/MyPerf4J/memory_metrics.log
BufPoolMetricsFile=/data/logs/MyPerf4J/buf_pool_metrics
ThreadMetricsFile=/data/logs/MyPerf4J/thread_metrics.log
RecorderMode=accurate
MilliTimeSlice=1000
IncludePackages=demo
Debug.PrintDebugLog=true

**Comment by LinShunKang** [comment]
你好，请改成： java -DMyPerf4JPropFile=/Users/abc/git/MyPerf4J/myPerf4J.properties
-javaagent:/Users/abc/git/MyPerf4J/MyPerf4J-ASM-2.1.0.jar demo/TestMyPerf

[image: image.png]

bergger <notifications@github.com> 于2019年1月5日周六 下午11:42写道：

**Comment by bergger** [comment]
谢谢了，后来我发现问题了，回复删除了，居然你还能看到，打扰了

**Comment by LinShunKang** [comment]
@bergger 没事儿 : )
