### ISSUE TITLE
IncludePackages  配置的使用

### ISSUE THREAD

**Issue by KahoChen** [LinShunKang/MyPerf4J#26]
com.test 里面有类 a1.java,b1.java ,c1.java
IncludePackages 怎么监控到具体的类
IncludePackages = com.test.[a1.java,b1.java] 这样貌似行不动

**Comment by LinShunKang** [comment]
你好，无需添加 `.java` 后缀：
`IncludePackages=com.test.[a1,b1] `

**Comment by KahoChen** [comment]
你好，可以了谢谢，另外想问一下，IncludePackages支持通配符的配法吗，例如com.test.*.service.impl,我试了一下好像是不支持的

**Comment by LinShunKang** [comment]
你好，目前暂不支持，这种利用 interface 来定义 DAO 的本质上是采用动态代理来实现的，对于 MyPerf4J 来说都是一个实现了 InvocationHandler 接口的实现类，目前 MyPerf4J 并没有针对某些框架进行这种适配。

**Comment by KahoChen** [comment]
谢谢你，那在作者的角度来看，想要把myperf4j适配成mybastis，用于监控dao，比如实现一个打点的接口，在应用里进行打点的监控（大概过程是new一个监控的对象A，方法结束时执行A.complete），这样的可行性是怎样的。但是我考虑到的一点是，myperf4j是无入侵性的工具，还不清楚能否实现类似的打点监控接口

**Comment by LinShunKang** [comment]
@KahoChen 你好，目前 MyPerf4J 已经支持针对 `java.lang.reflect.InvocationHandler` 实现类进行监控了：
* git clone git@github.com:LinShunKang/MyPerf4J.git
* git checkout feature/proxy_inject
* mvn clean package
