### ISSUE TITLE
能不能统计 spring 启动时框架里的方法执行时间

### ISSUE THREAD

**Issue by sangszhou** [LinShunKang/MyPerf4J#27]
测试了下, 似乎没看到. 创建的 controller 等方法的调用事件统计是没有问题的, 但是 spring 框架启动时的方法耗时统计信息没有, 暂时还没去看你的代码~

**Comment by sangszhou** [comment]
比如 AbstractApplicationContext.refresh 方法

**Comment by LinShunKang** [comment]
你好，MyPerf4J 默认把 org 开头的包都 exclude 了；如果你有需要可以修改 `cn.myperf4j.base.config.ProfilingFilter` 的代码
