### ISSUE TITLE
mvn clean package 出错

### ISSUE THREAD

**Issue by shengdoushi** [LinShunKang/MyPerf4J#29]
**Bug 描述** 
mvn clean package 出错

**运行环境**
1、JDK 版本

java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
 
2、运行容器和框架

3、操作系统

MacOS

**配置文件** 

无

**异常堆栈** 

[INFO]
[INFO] --- maven-surefire-plugin:2.20.1:test (default-test) @ MyPerf4J-Base ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MyPerf4J 2.3.0 ..................................... SUCCESS [  0.140 s]
[INFO] MyPerf4J-Base ...................................... FAILURE [  2.294 s]
[INFO] MyPerf4J-Core ...................................... SKIPPED
[INFO] MyPerf4J-ASM 2.3.0 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.561 s
[INFO] Finished at: 2019-01-27T21:53:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project MyPerf4J-Base: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test failed.: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :MyPerf4J-Base

**Comment by LinShunKang** [comment]
你好，请使用 JDK8 或者 JDK7 进行打包；或者直接下载 [MyPerf4J-ASM-2.3.0.jar](https://github.com/LinShunKang/Objects/blob/master/MyPerf4J-ASM-2.3.0.jar?raw=true)

**Comment by LinShunKang** [comment]
你好，是由于 maven-surefire-plugin 不支持 JDK11 的缘故，我已经升级到 2.22.0 了，你可以 checkout 到 develop 分支再次打包。

**Comment by shengdoushi** [comment]
更新后 已经可以了
