### ISSUE TITLE
可否增加各种metrics日志的保留时间？

### ISSUE THREAD

**Issue by gdlwolf** [LinShunKang/MyPerf4J#32]
**Bug 描述** 
请清晰和简洁的描述你遇见的 bug

可否增加各种metrics日志的保留时间？现在具备LogRollingTimeUnit回滚时间，但是无法设置回滚后的旧日志保留多久

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 

JDK8

2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等

Tomcat、SpringBoot

3、操作系统，例如，Linux、MacOS、Windows 等

Centos6、7

**配置文件** 
请把你的配置文件内容完整的复制出来

#应用名称
#AppName=MyPerf4JTest
AppName=tomcat00

#MetricsProcessor类型，0:以标准格式化结构输出到stdout.log 1:以标准格式化结构输出到磁盘  2:以InfluxDB LineProtocol格式输出到磁盘
MetricsProcessorType=2

#配置各个Metrics日志的文件路径，可不配置
MethodMetricsFile=/home/logs/method_metrics.log
ClassMetricsFile=/home/logs/class_metrics.log
GCMetricsFile=/home/logs/gc_metrics.log
MemMetricsFile=/home/logs/memory_metrics.log
BufPoolMetricsFile=/home/logs/buf_pool_metrics.log
ThreadMetricsFile=/home/logs/thread_metrics.log

#配置Record模式，可配置为accurate/rough
RecorderMode=accurate
   
#配置时间片，单位为ms，最小1s，最大600s
MilliTimeSlice=10000
   

#是否展示方法参数类型
ShowMethodParams=true

LogRollingTimeUnit=HOURLY
BackupRecordersCount=2
ExcludePrivateMethod=true
#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=com.demo.[p1,p2,p3]

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

没有异常

**Comment by LinShunKang** [comment]
你好，目前 MyPerf4J 还没有该功能，后续会考虑加入，感谢反馈。
另，可以先在 Linux 上配置 Cron 定时任务来完成。

**Comment by gdlwolf** [comment]
感谢。希望早点加入该功能，毕竟一台主机上可能会有多个java app，不同的app的日志文件路径又不一样，增加监控，卸载监控进而调整cron以及其对应的cron脚本，增加了维护成本。

**Comment by LinShunKang** [comment]
你好，增加了 `LogReserveCount` 配置参数，即为历史日志文件保留个数。请按以下步骤：
* git clone git@github.com:LinShunKang/MyPerf4J.git
* git checkout develop
* mvn clean package
