### ISSUE TITLE
多个应用可否公用相同的日志文件？是否会冲突？

### ISSUE THREAD

**Issue by gdlwolf** [LinShunKang/MyPerf4J#33]
**Bug 描述** 
请清晰和简洁的描述你遇见的 bug

多个应用可否公用相同的日志文件？是否会冲突？

假设我有两个应用：AppName=tomcat00   AppName=tomcat01
两个应用的配置文件中：xxxxMetricsFile我都设置为一样，且只有一个配置文件中我设置日志的回滚，那么所有的“同一台主机”上的多个java应用公用一个日志文件，对于一台主机上有多个java app来说非常方便。
但是不知道这样会否导致冲突？

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
JDK8
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
Tomcat8 SpringBoot1、2
3、操作系统，例如，Linux、MacOS、Windows 等

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

**Comment by LinShunKang** [comment]
你好，目前 MyPerf4J 不保证多进程写入文件的顺序，可能会导致文件内存的错乱。但是，如果 `MetricsProcessorType` 配置为 2，则可以把单个应用的所有 MetricsFile 配置为同一个文件；然后在 Telegraf 上配置 `files` 为模糊匹配即可。

**Comment by gdlwolf** [comment]
好的，我试试
