### ISSUE TITLE
 Method Metrics中能配置统计的时间单位吗？

### ISSUE THREAD

**Issue by gongmingbin** [LinShunKang/MyPerf4J#34]
使用 Method Metrics分析性能好像最小的时间单位是ms？当前导致如果方法执行时间不到1ms，显示的都是0ms。

**Comment by LinShunKang** [comment]
你好，目前的最小单位是 ms；如果需要更小的单位，你可以修改 `RoughRecorder` 和 `AccurateRecorder` 里的代码逻辑，把 `/ 1000000` 改成 `/ 100000` 那么单位就变成 0.1ms。
不过，ms 已经能满足绝大部分需求了，没必要比 ms 还小。

**Comment by gongmingbin** [comment]
好的，谢谢。项目是一个纯异步的项目，所以大部分method的执行都比较短。
