### ISSUE TITLE
telegraf如何跨服务器收集日志呢？我们使用的分布式，需要在每个服务器上都安装一个telegraf吗？有办法通过一个telegraf来统一收集日志吗？

### ISSUE THREAD

**Issue by MagnetoAndProfessorX** [LinShunKang/MyPerf4J#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LinShunKang** [comment]
你好，关于 Telegraf 跨服务器收集日志我没了解过；目前，我们是每一台服务器都部署一个 Telegraf 来收集 metrics 日志。
