### ISSUE TITLE
我修改了启动参数中 MyPerf4JPropFile 为其他名字，构建和启动的时候没问题，但是log中没有相关信息

### ISSUE THREAD

**Issue by chkch** [LinShunKang/MyPerf4J#37]
我修改的是这个文件 PropertyKeys.java 中的 String PRO_FILE_NAME = "MyPerf4JPropFile";

**Comment by chkch** [comment]
我修改的是  PropertyKeys.java 文件中的 String PRO_FILE_NAME = "MyPerf4JPropFile";
请问是否还有其他地方我没有了解到的地方需要修改

**Comment by LinShunKang** [comment]
你好，请按以下模板描述你的问题：

**问题描述** 
请清晰和简洁的描述你遇见的 问题

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
3、操作系统，例如，Linux、MacOS、Windows 等

**JVM启动参数** 
请把你的JVM启动参数完整的复制出来

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

PS：`IncludePackages` 需要配置你想要监控的包路径

**Comment by chkch** [comment]
抱歉，是 IncludePackages 参数写错了，导致没有获取到对应的Method 信息

**Comment by LinShunKang** [comment]
OK
