### ISSUE TITLE
告警中心

### ISSUE THREAD

**Issue by yushaojian** [LinShunKang/MyPerf4J#38]
**问题描述** 
你好，这个服务有集成告警组件么？当Java服务出现性能问题（崩溃边缘）时，需要发出告警消息。

**运行环境**
无

**JVM启动参数** 
无

**配置文件** 
无

**异常堆栈** 
无

**Comment by LinShunKang** [comment]
你好，MyPerf4J 本身并不支持告警功能；不过，你可以使用 Grafana 自带的告警功能。
