### ISSUE TITLE
能否支持下mysql持久化？

### ISSUE THREAD

**Issue by laradong** [LinShunKang/MyPerf4J#39]
毕竟现在用mysql也挺多的，持久化以后可以自己做数据图表，便于跟踪性能优化的情况。最好配套建表sql语句。感谢！

**Comment by LinShunKang** [comment]
你好，InfluxDB + Grafana 不能满足你的需求吗？之所以没选择 MySQL 的原因有两点：
* MySQL 不适合存储 metrics 类的数据，TSDB 更合适
* MySQL 需要预先创建表结构，而且 metrics 数据增加/减少时需要进行 DDL 操作，比较麻烦

**Comment by zhaozuolin** [comment]
进行内存分析，性能检测的都用时序数据库，就是influxDbB
