### ISSUE TITLE
GC监控建议使用JDK7引入的GC notification的机制

### ISSUE THREAD

**Issue by techzealot** [LinShunKang/MyPerf4J#41]
**你想要的功能和某一个问题相关？请详细描述它。**

GC信息不够详细，GC前后各区内存的变化，轮询也不够准确高效

**描述你想要的解决方式**

采用Java 7新推出的JMX API的GC notification机制可以获取更详细的GC信息

**描述你所构想的解决方式**

JMX API的GC notification

**其他相关内容**

**Comment by LinShunKang** [comment]
好的，我了解一下，目前这种定时调度的方式的确不太好

**Comment by LinShunKang** [comment]
GC 信息不够详细是缺少了什么？

**Comment by techzealot** [comment]
比如GC日志是这样：
[GC (Allocation Failure) [PSYoungGen: 147616K->16752K(153088K)] 204990K->74126K(502784K), 0.0319112 secs] [Times: user=0.12 sys=0.00, real=0.04 secs]
JMX的GcInfo对GC信息有封装可以使用

**Comment by LinShunKang** [comment]
MyPerf4J 除了没有区分 user、sys 和 real 外，都有了，你看看主页的 Grafana 截图

**Comment by techzealot** [comment]
是的，主要是GC发生的详细时间点不准确，感觉使用JMX标准接口对后续高版本的JDK能更好的支持

**Comment by LinShunKang** [comment]
其实，我之所以觉得定时不太好的原因和你相近，时间点不准确，导致采集出来的数据在 Grafana 上展示比较奇怪，我原来的想法是把采集 JVM 相关信息的时间间隔单独出来，按每秒采集一次就可以使采集的数据符合预期

**Comment by LinShunKang** [comment]
如果采用了JMX 的 Notification 接口是否会存在每次采集出来的数据都是 GC 后的内存空间，而无法展示在两次 GC 之间内存的变化的问题呢

**Comment by techzealot** [comment]
![image](https://user-images.githubusercontent.com/19412179/62407596-75382080-b5ed-11e9-992b-cfe59695d88a.png)
GCInfo有GC日志里基本上所有的信息，包括GC原因等，很全

**Comment by LinShunKang** [comment]
嗯，信息的确很全，但是仍然没有解决我所说的问题：无法知道在两次GC 之间内存的变化情况

**Comment by techzealot** [comment]
是的，内存变化还是得轮询

**Comment by LinShunKang** [comment]
那如果把 JVM 指标的采集时间间隔改为 1 秒，是不是就可以解决你所说的问题了呢？

**Comment by techzealot** [comment]
不清楚JMX API频繁调用是否会影响程序性能以及内存占用和GC

**Comment by LinShunKang** [comment]
应该还好，我找个时间测试一下。
PS：我司所有接入的服务，目前配置的都是10s，没发现问题

**Comment by LinShunKang** [comment]
我测试每秒采集一次 JVM 指标，并不会影响应用的 GC。
另外，我把 MilliTimeSlice 拆分为 MethodMilliTimeSlice 和 JvmMilliTimeSlice，分别控制方法指标的采集周期和 JVM 指标的采集周期，你可以用 develop 的分支重新打个包试试。

**Comment by techzealot** [comment]
ok，谢谢

**Comment by LinShunKang** [comment]
经过压测，性能也无影响；内存占用可以忽略，每秒一次并不算频繁
