### ISSUE TITLE
MyPerf4J是否支持打印正在运行的Java项目中所有被调用的（类名+方法名）？

### ISSUE THREAD

**Issue by 2994186010** [LinShunKang/MyPerf4J#42]
在不对Java应用程序做任何修改的前提下，是否能够打印所有被调用的（类名+方法名）？

**Comment by LinShunKang** [comment]
你好，MyPerf4J 不需要修改应用程序的代码，只需要在启动参数里加上：
* -javaagent:/your/path/to/MyPerf4J-ASM.jar
* -DMyPerf4JPropFile=/your/path/to/MyPerf4J.properties

需要重启应用才能生效
