### ISSUE TITLE
谁调用了这个方法long start = System.nanoTime() 和ProfilingAspect.profiling(start, methodId);

### ISSUE THREAD

**Issue by zheyiyi** [LinShunKang/MyPerf4J#44]
long start = System.nanoTime() 和ProfilingAspect.profiling(start, methodId);
System.nanoTime() 应该在onMethodEnter调用 和
ProfilingAspect.profiling 应该在onMehtodExit中调用 对吧， 但是为啥找不到 求教

    @Override
    protected void onMethodEnter() {
        if (profiling()) {
            maintainer.addRecorder(methodTagId, profilingConfig.getProfilingParam(innerClassName + "/" + methodName));

            mv.visitMethodInsn(INVOKESTATIC, "java/lang/System", "nanoTime", "()J", false);
            startTimeIdentifier = newLocal(Type.LONG_TYPE);
            mv.visitVarInsn(LSTORE, startTimeIdentifier);
        }
    }

    @Override
    protected void onMethodExit(int opcode) {
        if (profiling() && ((IRETURN <= opcode && opcode <= RETURN) || opcode == ATHROW)) {
            mv.visitVarInsn(LLOAD, startTimeIdentifier);
            mv.visitLdcInsn(methodTagId);
            mv.visitMethodInsn(INVOKESTATIC, PROFILING_ASPECT_INNER_NAME, "profiling", "(JI)V", false);
        }

**Comment by LinShunKang** [comment]
你好，纠正两点：
1、System.nanoTime() 的调用 是在 onMethodEnter 中生成的
2、ProfilingAspect.profiling() 的调用 是在 onMethodExit 中生成的

MyPerf4J 利用 ASM 在类加载的时候修改方法的字节码


zheyiyi <notifications@github.com> 于2019年9月23日周一 下午11:02写道：
