### ISSUE TITLE
原理图都加载不出来了

### ISSUE THREAD

**Issue by zheyiyi** [LinShunKang/MyPerf4J#45]
你好 原理图都加载不出来了

**Comment by LinShunKang** [comment]
你好，你是指 [实现原理](https://github.com/LinShunKang/MyPerf4J/wiki/实现原理) 里的图片吗？我看着没有问题的

**Comment by zheyiyi** [comment]
好了 我觉得刚才是 github 真个图都down了一段时间

LinShunKang <notifications@github.com> 于2019年10月7日周一 下午12:14写道：

**Comment by LinShunKang** [comment]
OK
