### ISSUE TITLE
关于jvmGcMetrics 问题

### ISSUE THREAD

**Issue by zheyiyi** [LinShunKang/MyPerf4J#46]
请问 为什么oldGCount - lastOldGcCount 被定义成 fullGcCount 而不是oldGcCount？

        JvmGcMetrics jvmGcMetrics = new JvmGcMetrics(
                youngGcCount - lastYoungGcCount,
                youngGcTime - lastYoungGcTime,
                oldGCount - lastOldGcCount,
                oldGcTime - lastOldGcTime);
 

    public JvmGcMetrics(long youngGcCount, long youngGcTime, long fullGcCount, long fullGcTime) {
        this.youngGcCount = youngGcCount;
        this.youngGcTime = youngGcTime;
        this.avgYoungGcTime = youngGcCount > 0L ? ((double) youngGcTime) / youngGcCount : 0D;
        this.fullGcCount = fullGcCount;
        this.fullGcTime = fullGcTime;
    }

**Comment by LinShunKang** [comment]
你好，目前一般不区分 OldGC(MajorGC) 和 FullGC，我是参考 `jstat` 的命名：
```
➜  ~ jstat -gcutil 13540 1000
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
  0.00 100.00  68.47   4.11  95.46  87.09     14    0.532     0    0.000    0.532
  0.00 100.00  68.47   4.11  95.46  87.09     14    0.532     0    0.000    0.532
  0.00 100.00  68.67   4.11  95.46  87.09     14    0.532     0    0.000    0.532
```
