### ISSUE TITLE
telegraf配置文件和我从官网下载最新一致，导致无法读取metrics

### ISSUE THREAD

**Issue by xiguizi** [LinShunKang/MyPerf4J#48]
**问题描述** 
telegraf配置文件和我从官网下载最新一致，导致无法读取metrics

官网的配置文件没有这个
[[inputs.tail]]
  files = ["/data/logs/MyPerf4J/metrics.log"]
  from_beginning = false
  pipe = false
  ## Method used to watch for file updates.  Can be either "inotify" or "poll".
  watch_method = "inotify"
  data_format = "influx"

我把这块加上，启动直接报错。

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
3、操作系统，例如，Linux、MacOS、Windows 等

**JVM启动参数** 
请把你的JVM启动参数完整的复制出来

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

**Comment by LinShunKang** [comment]
请把错误信息发出来

**Comment by LinShunKang** [comment]
1、[telegraf/v1.12/plugin-list](https://docs.influxdata.com/telegraf/v1.12/plugins/plugin-list/)
2、[nputs/tail/README.md](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/tail/README.md)

请用 command+F 或者 ctrl+F 查找 `tail`
