### ISSUE TITLE
请问介绍中influxDb 的截图是如何集成的呢?

### ISSUE THREAD

**Issue by xy83918** [LinShunKang/MyPerf4J#49]
**问题描述** 
请清晰和简洁的描述你遇见的 问题

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
3、操作系统，例如，Linux、MacOS、Windows 等

**JVM启动参数** 
请把你的JVM启动参数完整的复制出来

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

**Comment by xy83918** [comment]
找到相应的介绍: https://github.com/LinShunKang/MyPerf4J/wiki/InfluxDB_

**Comment by LinShunKang** [comment]
OK
