### ISSUE TITLE
你好，请教个问题，如果监控的方法有异常抛出，怎么处理？

### ISSUE THREAD

**Issue by zhuanshenlikai** [LinShunKang/MyPerf4J#50]
**问题描述** 
请清晰和简洁的描述你遇见的 问题

**运行环境**
1、JDK 版本号，例如，JDK7、JDK8 等 
2、运行容器和框架，例如，Tomcat、PlainJava、Spring、SpringBoot 等
3、操作系统，例如，Linux、MacOS、Windows 等

**JVM启动参数** 
请把你的JVM启动参数完整的复制出来

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

**Comment by LinShunKang** [comment]
你好，目前 MyPerf4J 会丢弃抛异常的那次记录，例如：监控方法 A 时，如果 A 方法调用了 100 次，其中有一次抛出异常，MyPerf4J 只会记录剩余的 99 次。

**Comment by zhuanshenlikai** [comment]
如果异常也需要监控，并且能记录下，用ASM可以做到么，有什么好的思路么？谢谢

**Comment by LinShunKang** [comment]
ASM 可以做到，至于怎么实现，你可以看看 [ASM4使用指南.pdf](https://github.com/LinShunKang/Objects/blob/master/docs/ASM4%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97.pdf?raw=true)，我之前尝试过，兼容性问题比较多就放弃了。

**Comment by JiaRG** [comment]
> 你好，目前 MyPerf4J 会丢弃抛异常的那次记录，例如：监控方法 A 时，如果 A 方法调用了 100 次，其中有一次抛出异常，MyPerf4J 只会记录剩余的 99 次。

@LinShunKang 会记录可用率的指标么

**Comment by LinShunKang** [comment]
> > 你好，目前 MyPerf4J 会丢弃抛异常的那次记录，例如：监控方法 A 时，如果 A 方法调用了 100 次，其中有一次抛出异常，MyPerf4J 只会记录剩余的 99 次。
> 
> @LinShunKang 会记录可用率的指标么

可用率指标指的是什么？如果指的是方法执行的成功率，那么目前不支持，毕竟目前还未对异常调用进行记录

**Comment by JiaRG** [comment]
好的

**Comment by LinShunKang** [comment]
@JiaRG @zhuanshenlikai 
我在 [feature/support_try_finally](https://github.com/LinShunKang/MyPerf4J/tree/feature/support_try_finally) 分支已针对普通方法实现使用 try-finally 的方式采集性能指标了：

原方法：
```
    public long getId1(long id) throws InterruptedException {
        return id + 1;
    }
```

使用 develop 分支打包的 MyPerf4J-ASM.jar 增强后：
```
    public long getId1(long id) throws InterruptedException {
        long var3 = System.nanoTime();
        long var10000 = id + 1L;
        ProfilingAspect.profiling(var3, 0);
        return var10000;
    }
```

使用 feature/support_try_finally 分支打包的 MyPerf4J-ASM.jar 增强后：
```
    public long getId1(long id) throws InterruptedException {
        long var3 = System.nanoTime();
        long var10000;
        try {
            var10000 = id + 1L;
        } finally {
            ProfilingAspect.profiling(var3, 0);
        }
        return var10000;
    }
```
