### ISSUE TITLE
telegraf配置了inputs.tail但是没有数据上传到influxdb

### ISSUE THREAD

**Issue by haoyisun** [LinShunKang/MyPerf4J#51]
**问题描述** 
请清晰和简洁的描述你遇见的 问题
你好，我按照流程配置了所有东西 "_metris.log"等文件也看到有内容输出，但是配置了telegraf并没有向influxdb输送inputs.tail指定的内容，现在influxdb没有关于JVM的任何数据

**运行环境**
1、JDK8 等
2、SpringBoot 等
3、Centos 7
4.  telegraf是1.13.0版本
5. influxdb是1.7.9版本

**JVM启动参数** 
请把你的JVM启动参数完整的复制出来

**配置文件** 
请把你的配置文件内容完整的复制出来

**异常堆栈** 
请把程序的错误栈信息完整的复制出来

**Comment by LinShunKang** [comment]
你好，有两种可能：
1、MetricsProcessorType 配置有问题，应该配置为 2
2、Telegraf 启动时间早于 `xxx_metrics.log`，需要杀死 Telegraf 进程后再次启动 Telegraf

**Comment by haoyisun** [comment]
好的，谢谢，我都尝试一下

**Comment by haoyisun** [comment]
你好，我把原来的日志删除了，并且重新整理了MyPref4J的配置文件，重启了java服务后，看到有日志输出，然后关掉了telegraf后又重新启动了，但是influxdb仍然没有数据
我的MyPref4J的配置如下：
`#应用名称
AppName=FlowProcessAgent

#MetricsProcessor类型
#0:以标准格式化结构输出到stdout.log 
#1:以标准格式化结构输出到磁盘
#2:以InfluxDB LineProtocol格式输出到磁盘
MetricsProcessorType=2

#配置各个Metrics 日志的文件路径，可配置成相同路径
MethodMetricsFile=/home/rocketai/tools/MyPerf4J/log/method_metrics.log
ClassMetricsFile=/home/rocketai/tools/MyPerf4J/log/class_metrics.log
GCMetricsFile=/home/rocketai/tools/MyPerf4J/log/gc_metrics.log
MemMetricsFile=/home/rocketai/tools/MyPerf4J/log/memory_metrics.log
BufPoolMetricsFile=/home/rocketai/tools/MyPerf4J/log/buf_pool_metrics.log
ThreadMetricsFile=/home/rocketai/tools/MyPerf4J/log/thread_metrics.log
FileDescMetricsFile=/home/rocketai/tools/MyPerf4J/log/file_desc_metrics.log
CompilationMetricsFile=/home/rocketai/tools/MyPerf4J/log/compilation_metrics.log

#配置Record模式，可配置为accurate/rough
RecorderMode=accurate

#配置方法指标的采集周期，单位为ms，最小1s，最大600s
MethodMilliTimeSlice=10000

#配置 JVM 指标的采集周期，单位为ms，最小1s，最大600s
JvmMilliTimeSlice=1000

#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=cn.rocketai.weixin.mp.*

#是否展示方法参数类型
ShowMethodParams=true`

我的telegraf配置如下：
`[global_tags]
  dc = ""
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "ms"
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
urls = ["http://127.0.0.1:8086"]
 database = "FlowProcessAgent"
  retention_policy = ""
 write_consistency = "any"
  timeout = "5s"

[[inputs.tail]]
   files=["/home/rocketai/tools/MyPerf4J/log/gc_metrics.log"]
 from_beginning = false
   pipe = false
   watch_method = "inotify"
   data_format = "influx"`

而且我开启了inputs.cpu、inputs.disk等，发现关于cpu、disk的metrics可以正常录入influxdb

**Comment by haoyisun** [comment]
> 你好，有两种可能：
> 1、MetricsProcessorType 配置有问题，应该配置为 2
> 2、Telegraf 启动时间早于 `xxx_metrics.log` 的生成时间，需要杀死 Telegraf 进程后再次启动 Telegraf

你好，我把原来的日志删除了，并且重新整理了MyPref4J的配置文件，重启了java服务后，看到有日志输出，然后关掉了telegraf后又重新启动了，但是influxdb仍然没有数据

*我的MyPref4J的配置如下：*
```
#应用名称
AppName=FlowProcessAgent

#MetricsProcessor类型
#0:以标准格式化结构输出到stdout.log
#1:以标准格式化结构输出到磁盘
#2:以InfluxDB LineProtocol格式输出到磁盘
MetricsProcessorType=2

#配置各个Metrics 日志的文件路径，可配置成相同路径
MethodMetricsFile=/home/rocketai/tools/MyPerf4J/log/method_metrics.log
ClassMetricsFile=/home/rocketai/tools/MyPerf4J/log/class_metrics.log
GCMetricsFile=/home/rocketai/tools/MyPerf4J/log/gc_metrics.log
MemMetricsFile=/home/rocketai/tools/MyPerf4J/log/memory_metrics.log
BufPoolMetricsFile=/home/rocketai/tools/MyPerf4J/log/buf_pool_metrics.log
ThreadMetricsFile=/home/rocketai/tools/MyPerf4J/log/thread_metrics.log
FileDescMetricsFile=/home/rocketai/tools/MyPerf4J/log/file_desc_metrics.log
CompilationMetricsFile=/home/rocketai/tools/MyPerf4J/log/compilation_metrics.log

#配置Record模式，可配置为accurate/rough
RecorderMode=accurate

#配置方法指标的采集周期，单位为ms，最小1s，最大600s
MethodMilliTimeSlice=10000

#配置 JVM 指标的采集周期，单位为ms，最小1s，最大600s
JvmMilliTimeSlice=1000

#需要监控的package，可配置多个，用英文';'分隔
IncludePackages=cn.rocketai.weixin.mp.*

#是否展示方法参数类型
ShowMethodParams=true
```

*我的telegraf配置如下：*
```
[global_tags]
dc = ""
[agent]
interval = "1s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "1s"
flush_jitter = "0s"
precision = "ms"
debug = false
quiet = false
hostname = ""
omit_hostname = false

[[outputs.influxdb]]
urls = ["http://127.0.0.1:8086"]
database = "FlowProcessAgent"
retention_policy = ""
write_consistency = "any"
timeout = "5s"

[[inputs.tail]]
files=["/home/rocketai/tools/MyPerf4J/log/gc_metrics.log"]
from_beginning = false
pipe = false
watch_method = "inotify"
data_format = "influx"
```

而且我开启了inputs.cpu、inputs.disk等，发现关于cpu、disk的metrics可以正常录入influxdb

**Comment by haoyisun** [comment]
tail查看日志格式如下：
```
jvm_gc_metrics_v2,AppName=FlowProcessAgent YoungGcCount=0i,YoungGcTime=0i,AvgYoungGcTime=0.00,FullGcCount=0i,FullGcTime=0i,ZGcTime=0i,ZGcCount=0i,AvgZGcTime=0.00 1578369698008000000
jvm_gc_metrics_v2,AppName=FlowProcessAgent YoungGcCount=0i,YoungGcTime=0i,AvgYoungGcTime=0.00,FullGcCount=0i,FullGcTime=0i,ZGcTime=0i,ZGcCount=0i,AvgZGcTime=0.00 1578369699008000000
jvm_gc_metrics_v2,AppName=FlowProcessAgent YoungGcCount=0i,YoungGcTime=0i,AvgYoungGcTime=0.00,FullGcCount=0i,FullGcTime=0i,ZGcTime=0i,ZGcCount=0i,AvgZGcTime=0.00 1578369700008000000
```

**Comment by LinShunKang** [comment]
你好，根据你的描述，MyPerf4J 工作正常，Telegraf 收集 CPU 内存等信息也正常，那么很可能就出在 Telegraf 读取 metrics.log 并上报给 InfluxDB 这个流程。尝试从下面两个方向定位问题：
1、在终端进入 InfluxDB，查看是否存在 FlowProcessAgent 这个 database，如果没有，尝试第 2 点
2、修改 Telegraf 的配置文件的 `watch_method = "poll"` 再重启 Telegraf

**Comment by haoyisun** [comment]
> 你好，根据你的描述，MyPerf4J 工作正常，Telegraf 收集 CPU 内存等信息也正常，那么很可能就出在 Telegraf 读取 metrics.log 并上报给 InfluxDB 这个流程。尝试从下面两个方向定位问题：
> 1、在终端进入 InfluxDB，查看是否存在 FlowProcessAgent 这个 database，如果没有，尝试第 2 点
> 2、修改 Telegraf 的配置文件的 `watch_method = "poll"` 再重启 Telegraf

我检查了一下influxdb是存在FlowProcessAgent这个库的，为了防止是库名输入错误，我把FlowProcessAgent这个库删掉了，又修改 Telegraf 的配置文件的 watch_method = "poll" 再重启 Telegraf，influxdb重新创建了FlowProcessAgent库，但是还是没有数据进来，也没有对应的表生成

**Comment by LinShunKang** [comment]
你好，Telegraf 的日志没关系，只是时区不同而已。"1578454674003000000" 是 `System.currentTimeMillis() * 1000_000` 得到的数值，因为 InfluxDB 默认采用 纳秒 作为时间戳的单位。

**Comment by LinShunKang** [comment]
我发现你贴出来的 Telegraf 的配置文件没有缩进，确认一下是否有问题？

**Comment by LinShunKang** [comment]
还有，重启 Telegraf 和 InfluxDB 后 xxx_metrics.log 是否一直保持有日志不断的输出？

**Comment by danileyang** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by wudongwang** [comment]
解决了吗，兄弟

**Comment by wudongwang** [comment]
> > 你好，根据你的描述，MyPerf4J 工作正常，Telegraf 收集 CPU 内存等信息也正常，那么很可能就出在 Telegraf 读取 metrics.log 并上报给 InfluxDB 这个流程。尝试从下面两个方向定位问题：
> > 1、在终端进入 InfluxDB，查看是否存在 FlowProcessAgent 这个 database，如果没有，尝试第 2 点
> > 2、修改 Telegraf 的配置文件的 `watch_method = "poll"` 再重启 Telegraf
> 
> 我检查了一下influxdb是存在FlowProcessAgent这个库的，为了防止是库名输入错误，我把FlowProcessAgent这个库删掉了，又修改 Telegraf 的配置文件的 watch_method = "poll" 再重启 Telegraf，influxdb重新创建了FlowProcessAgent库，但是还是没有数据进来，也没有对应的表生成，另外，我启动telegraf后的日志输出是这样的：
> 
> ```
> 2020-01-08T03:10:40Z I! Loaded inputs: tail
> 2020-01-08T03:10:40Z I! Loaded aggregators: 
> 2020-01-08T03:10:40Z I! Loaded processors: 
> 2020-01-08T03:10:40Z I! Loaded outputs: influxdb
> 2020-01-08T03:10:40Z I! Tags enabled: dc= host=111.231.83.249-bxbtest
> 2020-01-08T03:10:40Z I! [agent] Config: Interval:1s, Quiet:false, Hostname:"111.231.83.249-bxbtest", Flush Interval:1s
> ```
> 
> 在这之后就没有日志输出了，并且我的telegraf 日志 的时间有点问题，与当前时间相差8个小时，比如上面日志显示的是“2020-01-08T03:10:40Z”，但实际日志打印的时间是"2020-01-08T11:10:40Z";
> 
> 还有一点疑问的是我查看了一下thread_metrics.log的日志，抽取了一个样例：
> 
> ```
> jvm_thread_metrics,AppName=FlowProcessAgent TotalStarted=1137i,Active=53i,Peak=54i,Daemon=45i,New=0i,Runnable=9i,Blocked=0i,Waiting=29i,TimedWaiting=15i,Terminated=0i 1578454674003000000
> ```
> 
> 截取了最后一个数值“1578454674003000000”，请问这个是时间戳吗，我把这个在Java里用new Date输出了一下，发现数值有些大

解决了吗，兄弟。
