### ISSUE TITLE
请问能支持tomcat么

### ISSUE THREAD

**Issue by liubaojunsh** [LinShunKang/MyPerf4J#52]
Tomcat里的服务怎么监控

**Comment by LinShunKang** [comment]
可以，包括 独立部署的 Tomcat 和 SpringBoot 内置的 Tomcat 都支持。
直接修改 MyPerf4J.properties 配置文件中的 IncludePackages 为你想要监控的包即可。

请参考：[关于包路径规则](https://github.com/LinShunKang/MyPerf4J/wiki/%E9%85%8D%E7%BD%AE#%E5%85%B3%E4%BA%8E%E5%8C%85%E8%B7%AF%E5%BE%84%E8%A7%84%E5%88%99)
