### ISSUE TITLE
请问有方法可以让myperf4j-asm.jar支持jdk6吗？

### ISSUE THREAD

**Issue by studyzyq** [LinShunKang/MyPerf4J#53]
**问题描述** 
项目的环境用的是jdk6运行的，用到了很多其他组件，暂时没法直接升到jdk7及以上，请问有没有办法在源码这一层编译出一个myperf4j-asm.jar可在jdk6下运行的版本？非常感谢

**Comment by LinShunKang** [comment]
你可以试试，我没安装 JDK6

**Comment by studyzyq** [comment]
我安装JDK6试了，编译报错。主要是很多类里面用了JDK7的泛型推断特性、阻塞队列比如：LinkedTransferQueue，BufferPoolMXBean等，JDK6不支持。
泛型指型推断的可以我直接改成jdk6支持的方式了，但是还有MyPerf4J-Base模块下有4个类用了jdk7的特性。主要是：
```
MyPerf4J-Base\src\main\java\cn\myperf4j\base\metric\JvmBufferPoolMetrics.java
MyPerf4J-Base\src\main\java\cn\myperf4j\base\buffer\IntBufPool.java
MyPerf4J-Base\src\main\java\cn\myperf4j\base\log\AutoRollingLogger.java
MyPerf4J-Base\src\main\java\cn\myperf4j\base\metric\formatter\impl\DefMethodMetricsFormatter.java
```
能否帮忙修改一版支持jdk6的版本呢？谢谢！

**Comment by LinShunKang** [comment]
我没有使用 JDK6 的场景，你可以自己修改代码支持 JDK6
