### ISSUE TITLE
全套安装部署太麻烦了，log中的指标说明没有吗？LightWeightScheduler.runTask这些日志有何用？influxdb telegraf头一回听说

### ISSUE THREAD

**Issue by liuwei88212** [LinShunKang/MyPerf4J#57]
**你想要的功能和某一个问题相关？请详细描述它。**
清晰和简要的描述你所遇到的问题。

**描述你想要的解决方式**
清晰和简要描述你想要的解决方式。

**描述你所构想的解决方式**
清晰和简要描述你思考过的可行方式。

**其他相关内容**
在这里添加与该功能相关的其他上下文内容或者截图。

**Comment by LinShunKang** [comment]
* 指标说明在 [这里](https://github.com/LinShunKang/MyPerf4J/wiki/%E6%8C%87%E6%A0%87)，README 中有链接
* LightWeightScheduler.runTask 是 Debug 日志，你开启了就有
* InfluxDB 是一个时序数据库，你如果需要在 Grafana 中展示就需要把 Metrics 存入 InfluxDB 中；另外，MyPerf4J 3.0 已经可以不依赖 Telegraf 了，具体请看 [这里](https://github.com/LinShunKang/MyPerf4J/wiki/%E6%9E%B6%E6%9E%84)
* 至于安装部署，3.0 已经做到最简单了，MyPerf4J + InfluxDB + Grafana，没有比这个更简单的架构了

**Comment by wyyl1** [comment]
我觉得3.0的部署方式在可接受的范围之内。负载不高的情况下用于收集运行数据是一个很不错的选择。
比Cat部署简单了很多。
做压力测试的时候，可以先保存在本地日志文件，测试结束后在同步到InfluxDB，可以避免测试中的网络开销。

**Comment by LinShunKang** [comment]
> 我觉得3.0的部署方式在可接受的范围之内。负载不高的情况下用于收集运行数据是一个很不错的选择。
> 比Cat部署简单了很多。
> 做压力测试的时候，可以先保存在本地日志文件，测试结束后在同步到InfluxDB，可以避免测试中的网络开销。

其实，MyPerf4J 采集出来的指标占用的空间是比较小的，如果是采用日志方式采集的话，1 天下来不到 2GB 的空间，所以，就算是压测时也可以直接发送 Metrics 到 InfluxDB，并不会占用多少网卡带宽。

**Comment by wyyl1** [comment]
下次压测的时候感受一下。
压测的时候一般是针对某个方法，只需要记录测试链路相关的数据，数据量应该更小。
