### ISSUE TITLE
如何监控MyPerf4J自身的性能？

### ISSUE THREAD

**Issue by wyyl1** [LinShunKang/MyPerf4J#59]
**问题描述**

如何监控MyPerf4J自身的性能？

我在MyPerf4J.properties中配置了，但不起作用

```properties
filter.packages.include = cn.myperf4j.*;
```

在ProfilingFilter.java中看到了

```java
// 不注入 MyPerf4J 本身
excludePackagePrefix.add("cn/myperf4j/");
```

**运行环境**
* MyPerf4J 3.0.0
* JDK8
* Tomcat、SpringBoot
* Linux

**Comment by LinShunKang** [comment]
你好，MyPerf4J 没必要监控自身的性能消耗吧，如果用 MyPerf4J 监控自身的话，会出现无限递归的问题。你可以把代码注释掉，尝试一下：）

PS: 如果你需要分析 MyPerf4J 的性能消耗，可以借助其它监控工具，例如 [async-profiler](https://github.com/jvm-profiling-tools/async-profiler)，或者使用 JMH 进行压测，验证 MyPerf4J 的高性能。

**Comment by wyyl1** [comment]
谢谢
