### ISSUE TITLE
响应时间数据全量输出

### ISSUE THREAD

**Issue by ImSingee** [LinShunKang/MyPerf4J#65]
**你想要的功能和某一个问题相关？请详细描述它。**
希望可以支持完全输出某方法的响应时间数据，而非简单返回 max min avg 等分析结果数据

**描述你想要的解决方式**
增加一个新的方法 metric，会在监控周期结束后向 influxdb 发送所有的响应数据

**描述你所构想的解决方式**

**其他相关内容**
另外，可否在 influxdb label 中添加 package？

**Comment by LinShunKang** [comment]
我有一个疑问，为什么要输出所有的响应时间呢？
