### ISSUE TITLE
更高精度

### ISSUE THREAD

**Issue by ImSingee** [LinShunKang/MyPerf4J#66]
**你想要的功能和某一个问题相关？请详细描述它。**
我们目前的产品的方法平均响应时间已经在 1ms 以下了，MyPerf4J 上报的信息精度仅仅毫秒级别无法进行进一步优化

**描述你想要的解决方式**
目前 ASM 中上报使用的是 System.nanoSeconds ，因此理论上是可以支持纳秒级别信息的（虽然没有纳秒级别精度，但作为一个相关量比对已经足够了）

**描述你所构想的解决方式**
在配置中增加精度设置，允许提高各个指标的精度。

**其他相关内容**

**Comment by LinShunKang** [comment]
你好，一般来说，评估一个方法响应时间的好坏，我们更多的采用 TP99、TP999 等来体现响应时间的分布情况，所以，无论平均时间是否小于 1ms，TP999 都是极具参考价值的；而目前 MyPerf4J 是采用空间换时间的方式来尽可能的提高性能，所以无法将时间精度提高的微秒甚至纳秒级，而且，一般也没有这个需求场景。
