### ISSUE TITLE
启动myperf4j报NoClassDefFoundError

### ISSUE THREAD

**Issue by linjin123** [LinShunKang/MyPerf4J#69]
**问题描述**

启动myperf4j报NoClassDefFoundError，大佬帮忙看看谢谢

**运行环境**
* MyPerf4J 版本号3.1.0 
* JDK 版本号 JDK8 
* 运行容器和框架，SpringBoot 
* 操作系统，Linux

**JVM启动参数** 

![3](https://user-images.githubusercontent.com/42064777/105439571-0f879a80-5ca0-11eb-8bfb-7c1dec9e4960.png)
![4](https://user-images.githubusercontent.com/42064777/105439595-1a422f80-5ca0-11eb-8603-c11f437e1077.png)

**配置文件** 

![1](https://user-images.githubusercontent.com/42064777/105439635-2cbc6900-5ca0-11eb-8696-de4be50d2e73.png)

**异常堆栈** 

![2](https://user-images.githubusercontent.com/42064777/105439659-380f9480-5ca0-11eb-899f-c12229db14d8.png)

**Comment by LinShunKang** [comment]
你好，有 2 个问题：
* SpringBoot 的版本号是多少？
* 异常堆栈信息能否提供完善一些？
