### ISSUE TITLE
请问是否支持自定义埋点监控

### ISSUE THREAD

**Issue by fanchw** [LinShunKang/MyPerf4J#73]
**问题描述**
目前只有基于方法method的监控，是否支持自定义的埋点进行监控？自定监控的数据是否可以和通用监控一起输出？

**Comment by LinShunKang** [comment]
你好，不支持

**Comment by JiaRG** [comment]
@LinShunKang 这个有计划支持么，这算一个比较常规的需求吧

**Comment by LinShunKang** [comment]
> @LinShunKang 这个有计划支持么，这算一个比较常规的需求吧

MyPerf4J 是一个 JavaAgent，就算是支持自定义 业务代码也无法访问指定的类和方法（反射除外）

**Comment by JiaRG** [comment]
我的设想是这样的：提供一个sdk，sdk负责计算埋点的数据，然后通过 http 或 rpc 的方式上报给 agent 由agent负责写入日志，或者直接将数据按照agent的格式写入到日志。不知道对不对哈

**Comment by LinShunKang** [comment]
> 我的设想是这样的：提供一个sdk，sdk负责计算埋点的数据，然后通过 http 或 rpc 的方式上报给 agent 由agent负责写入日志，或者直接将数据按照agent的格式写入到日志。不知道对不对哈

MyPerf4J 是一个 JavaAgent，JavaAgent 是在 JVM 启动时加载的，MyPerf4J 所属的进程和应用 JVM 是同一个进程，不是那种独立运行的 Agent
