### ISSUE TITLE
docker中运行MyPerf4J遇到得问题

### ISSUE THREAD

**Issue by 284330505** [LinShunKang/MyPerf4J#74]
**问题描述**
我们得jar包是在 docker中运行得，在 docker中使用MyPerf4J，发现日志并不能打印到指定得目录中，而是打印在控制台里面？请问这个有什么解决办法吗？

**Comment by LinShunKang** [comment]
能把 MyPerf4J.properties 文件内容发出来吗？

284330505 ***@***.***>于2021年6月2日 周三10:38写道：
