### ISSUE TITLE
收集的数据是否可在Grafana中进行预警

### ISSUE THREAD

**Issue by wuyue233** [LinShunKang/MyPerf4J#78]
Grafana中使用项目提供的InfluxDB v1.x [Method Dashboard]模板在预警窗口中提示Template variables are not supported in alert queries， 原因是模板中的json文件中有一些变量 ，我看下变量是"AppName" =~ /^$Application$/ AND "ClassName" =~ /^$ApiImpl$/是动态的所以才这样提示，需要改成固定的，如果固定的话 多个项目话就用不了，有没有解决方案

**Comment by LinShunKang** [comment]
这个没有办法彻底解决，你只能创建一个专用的 Dashboard，然后在这个 Dashboard 里为不同应用的不同方法指标配置不同的报警规则
