### ISSUE TITLE
采用ibm websphere 监控 日志下没发输出

### ISSUE THREAD

**Issue by xiguizi** [LinShunKang/MyPerf4J#80]
**问题描述**

请清晰和简洁的描述你遇见的 问题

**运行环境**
* MyPerf4J 版本号，最新版本
* JDK 版本号，IBM open JDK8 等 
* 运行容器和框架， websphere 等
* 操作系统，例如，Linux 等

**JVM启动参数** 
已按照要求增加
-javaagent:/home/wasadmin/MyPerf4J-ASM-3/MyPerf4J-ASM.jar -DMyPerf4JPropFile=/home/wasadmin/MyPerf4J-ASM-3/MyPerf4J.properties
请把你的JVM启动参数完整的复制出来

其他没变化 ，日志目录下没有任何输出，
**配置文件** 

请把你的配置文件内容完整的复制出来

**异常堆栈** 

请把程序的错误栈信息完整的复制出来

**Comment by LinShunKang** [comment]
请把你的配置文件内容完整的复制出来
