### ISSUE TITLE
已经整合了grafana、influxdb，MyPerf4J已经往influxdb表中写入了数据，grafana页面使用MyPerf4J模板无法展示数据

### ISSUE THREAD

**Issue by q920447939** [LinShunKang/MyPerf4J#81]
**问题描述**

请清晰和简洁的描述你遇见的 问题

**运行环境**
* MyPerf4J 版本号  3.2.0
* JDK 版本号，JDK8 等 
* 运行容器和框架，SpringBoot 
* 操作系统，例如，Linux+Windows 等

**JVM启动参数** 
```
java -javaagent:MyPerf4J-ASM-3.2.0-SNAPSHOT.jar  -Dspring.profiles.active=test56 -DMyPerf4JPropFile=F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/myPerf4J.properties -jar cgdm-provider.jar
```

**配置文件** 
```
# MyPerf4J 所有配置请参考：https://github.com/LinShunKang/MyPerf4J/wiki/%E9%85%8D%E7%BD%AE

# 配置监控应用的名称
app_name = kb-data-rest

debug = true

###############################################################################
#                           Metrics Configuration                             #
###############################################################################

# 配置 MetricsExporter 类型
#       log.stdout:     以标准格式化结构输出到 stdout.log
#       http.influxdb:  以 InfluxDB LineProtocol 格式发送至 InfluxDB server，需要另行增加 influxdb 的配置
metrics.exporter = http.influxdb

# 配置各项监控指标日志的文件路径
# 如果 metrics.exporter 配置为 log.influxdb，建议把所有的 metrics.log.* 路径配置成一样以方便 Telegraf 收集
metrics.log.method = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.class_loading = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.gc = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.memory = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.buff_pool =F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.thread = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.file_desc = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log
metrics.log.compilation = F:/liming/work_space/tzjk/git_work_space/cgdm450/cgdm-provider/target/MyPerf4J/metrics.log


###############################################################################
#                           Filter Configuration                              #
###############################################################################

# 配置需要监控的package，可配置多个，用英文';'分隔
#   com.demo.p1 代表包含以 com.demo.p1 为前缀的所有包和类
#   [] 表示集合的概念：例如，com.demo.[p1,p2,p3] 代表包含以 com.demo.p1、com.demo.p2 和 com.demo.p3 为前缀的所
#有包和类，等价于 com.demo.p1;com.demo.p2;com.demo.p3
#   * 表示通配符：可以指代零个或多个字符，例如，com.*.demo.*
filter.packages.include = com.*;

# 配置不需要监控的package，可配置多个，用英文';'分隔
#filter.packages.exclude = cn.perf4j.demo.dao.DemoDAOImpl


influxdb.host=172.18.200.166
influxdb.port=8086
influxdb.database=influxdb
influxdb.username=influx
influxdb.password=influxdb
influxdb.conn_timeout=3000
influxdb.read_timeout=5000

```

**异常堆栈** 
```
无
```

influxdb 数据如图：
https://imgloc.com/i/U4cZF

grafana如图：
https://imgloc.com/i/U4mOH

按着教程来的，但是grafana无数据

**Comment by LinShunKang** [comment]
情检查以下几项：
* 数据源是否配置以及是否配置正确
* Dashboard 是否选择的正确的数据源，包括 setting 和 panel 中的数据源

**Comment by daxiondi** [comment]
![image](https://user-images.githubusercontent.com/26639571/209797600-ce96ee11-7915-4faa-a7c5-a017e60821f5.png)
和你一样的问题，需要把这里json的bucket给改了，默认是MyPerf4J
@q920447939

**Comment by q920447939** [comment]
> ![image](https://user-images.githubusercontent.com/26639571/209797600-ce96ee11-7915-4faa-a7c5-a017e60821f5.png) 和你一样的问题，需要把这里json的bucket给改了，默认是MyPerf4J @q920447939

我在influxdb2.x 创建了 bucket 为 `MyPerf4J` 。但是我发现 demo spring boot项目MyPerf4J插件启动会提示`create database 
 401`(这个应该是和`influxdb`增加了token的机制把，猜测是登录失败导致写入不了数据)。
然后我想着可能这个插件只支持influxdb1.x把 . 然后启动demo 程序又能正常的往influxdb1.x 数据库里面写数据。但是grafana依然无数据。不过我推测是因为作者grafana写了两个版本的grafana json文件导致的。 v1和v2的grafana不兼容把。但是v1的grafana地址找不到  难受的一笔

**Comment by q920447939** [comment]
https://github.com/LinShunKang/MyPerf4J/wiki/Grafana 中的  InfluxDB v1.x 下的 `Method Dashboard ` 和 `JVM Dashboard`地址已失效，建议更新 。
 V1  版本老地址 https://grafana.com/grafana/dashboards/7766-myperf4j-influxdb-method/  、https://grafana.com/grafana/dashboards/8787-myperf4j-influxdb-jvm/

**Comment by LinShunKang** [comment]
> https://github.com/LinShunKang/MyPerf4J/wiki/Grafana 中的 InfluxDB v1.x 下的 `Method Dashboard ` 和 `JVM Dashboard`地址已失效，建议更新 。 V1 版本grafana 老地址 https://grafana.com/grafana/dashboards/7766-myperf4j-influxdb-method/ 、https://grafana.com/grafana/dashboards/8787-myperf4j-influxdb-jvm/

应该是 Grafana 的链接不兼容：原来是 https://grafana.com/dashboards/7766 改成 https://grafana.com/grafana/dashboards/7766 后就可以了
