### ISSUE TITLE
tomcat8.5没有打出日志

### ISSUE THREAD

**Issue by sheldon-xie** [LinShunKang/MyPerf4J#86]
环境：win10
在tomcat8.5的/bin下写了一个setenv.bat,内容如下：
```
set JAVA_OPTS="-javaagent:D:\\tools\\MyPerf4J-ASM-3.3.0\\MyPerf4J-ASM-3.3.0-SNAPSHOT.jar=appCode=10000"
set JAVA_OPTS="-DMyPerf4JPropFile=D:\\tools\\MyPerf4J-ASM-3.3.0\\MyPerf4J.properties"
```
MyPerf4J.properties 内容如下：
![image](https://user-images.githubusercontent.com/10841796/222883215-a36e3f3d-fffa-4231-9ef5-ed8463c8aa13.png)

日志文件打在：D:\\tools\\MyPerf4J-ASM-3.3.0\\logs\\下，
然后，启动tomca成功，一直没打出日志来；

**Comment by LinShunKang** [comment]
你好，你看看 catalinaout.log

**Comment by sheldon-xie** [comment]
> 

刚又部署在centos系统上了，也是没有日志；但是，在catalina.log里有；

**Comment by LinShunKang** [comment]
嗯，因为你把 metrics.export 配置为了 log.stdout，这个配置值的意思是把指标输出到标准输出中，在 tomcat 里就是 catalina.out 文件；如果你想要输出到指定的文件中，应该配置为 log.standard

**Comment by JiaRG** [comment]
@LinShunKang `filter.packages.include = com.*;org.apache;` 监控 tomcat 本身的时候会报错 `ClassNotFoundException`

我调试了下发现 `org/apache/` 包下的类，在构造 ClassWriter 的时候用 `ClassWriter.COMPUTE_MAXS`  就好使了

**Comment by JiaRG** [comment]
https://github.com/LinShunKang/MyPerf4J/blob/4c0a98d8f0f93733b0fddbb2b4b3dd4edd32470d/MyPerf4J-Base/src/main/java/cn/myperf4j/base/config/ProfilingFilter.java#L87-L97

还有这块为啥要把内部类给过滤掉呢？
