### ISSUE TITLE
关于ASM COMPUTE_FRAMES COMPUTE_MAXS的讨论

### ISSUE THREAD

**Issue by JiaRG** [LinShunKang/MyPerf4J#89]
**问题描述**

目前源码中假如检测到类名和方法名中存在 $ 符号就会跳过注入

https://github.com/LinShunKang/MyPerf4J/blob/4c0a98d8f0f93733b0fddbb2b4b3dd4edd32470d/MyPerf4J-Base/src/main/java/cn/myperf4j/base/config/ProfilingFilter.java#L87-L97

https://github.com/LinShunKang/MyPerf4J/blob/4c0a98d8f0f93733b0fddbb2b4b3dd4edd32470d/MyPerf4J-Base/src/main/java/cn/myperf4j/base/config/ProfilingFilter.java#L182-L190

**Comment by LinShunKang** [comment]
现在 MyPerf4J 只支持 1.7 及其之上的版本，这个改动的影响面比较大，你测试了哪些场景？

这块代码逻辑兼容了 PlainJava、Tomcat、SpringBoot、Flink 等场景，如果你的解决方案同样适用这些场景的话，欢迎提交 PR

**Comment by LinShunKang** [comment]
这种写法你是在哪儿看到的？当年我写这段代码的时候对于使用 COMPUTE_MAXS 还是 COMPUTE_FRAMES 还是比较困惑的

**Comment by LinShunKang** [comment]
有想法、运气不错；不过，你这个改动得进行全面的测试才行

**Comment by LinShunKang** [comment]
> 翻了下文档，读的时候不需要计算，要不会有性能损耗，写的时候才重新计算

这个方案有问题：
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/7189879/230759895-1f7ebd2b-8e24-4ec3-8069-d64edcd48240.png">

**Comment by LinShunKang** [comment]
> 这是跟其它的 agent 冲突了吧，我本地用 jdk20 起了一个 springboot2.7.8 的 demo 没问题

不是

**Comment by LinShunKang** [comment]
> ![image](https://user-images.githubusercontent.com/31472350/230924650-b28f7300-14b0-4ec9-bc2d-1ac5c0f1613d.png)
> 
> 出现了个这问题😓
> 
> ```
> 2023-04-10 22:38:00.014 [MyPerf4J] ERROR [MyPerf4J-LightWeightScheduler-0] JvmMetricsScheduler.processThreadMetrics(1681137420014, 1681137420014, 1681137480014) Could not initialize class cn.myperf4j.base.metric.collector.JvmThreadCollector
> java.lang.NoClassDefFoundError: Could not initialize class cn.myperf4j.base.metric.collector.JvmThreadCollector
>         at cn.myperf4j.core.scheduler.JvmMetricsScheduler.processThreadMetrics(JvmMetricsScheduler.java:139)
>         at cn.myperf4j.core.scheduler.JvmMetricsScheduler.run(JvmMetricsScheduler.java:72)
>         at cn.myperf4j.core.LightWeightScheduler.runTask(LightWeightScheduler.java:100)
>         at cn.myperf4j.core.LightWeightScheduler.runAllTasks(LightWeightScheduler.java:93)
>         at cn.myperf4j.core.LightWeightScheduler.access$200(LightWeightScheduler.java:18)
>         at cn.myperf4j.core.LightWeightScheduler$1.run(LightWeightScheduler.java:85)
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
>         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
>         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
>         at java.base/java.lang.Thread.run(Thread.java:1623)
> Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make private static native java.lang.Thread[] java.lang.Thread.getThreads() accessible: module java.base does not "opens java.lang" to unnamed module @6a41eaa2 [in thread "MyPerf4J-LightWeightScheduler-1"]
>         at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
>         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
>         at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
>         at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
>         at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
>         at cn.myperf4j.base.metric.collector.JvmThreadCollector.reflectGetThreadsMethod(JvmThreadCollector.java:34)
>         at cn.myperf4j.base.metric.collector.JvmThreadCollector.<clinit>(JvmThreadCollector.java:27)
>         ... 12 more
> ```

注意看：module java.base does not "opens java.lang" to unnamed module

**Comment by LinShunKang** [comment]
> ThreadMXBean 里面不是有现成的方法可以获取到数据么，为啥要反射呢？

性能差，线程数很多时会影响应用

**Comment by LinShunKang** [comment]
> > > 这是跟其它的 agent 冲突了吧，我本地用 jdk20 起了一个 springboot2.7.8 的 demo 没问题
> > 
> > 
> > 不是
> 
> 有复现的 demo 么，图里也看不出啥来，或者加载的那个类有啥特别的

从代码上看没什么特别的：
* `class A extends B`
* 在加载 B 时抛出 `java.lang.ClassCircularityError: A`

**Comment by LinShunKang** [comment]
你试试这个方案：
```
    private byte[] getBytes(final ClassLoader loader,
                            String className,
                            byte[] classFileBuffer) {
        final ClassReader cr = new ClassReader(classFileBuffer);
        final ClassWriter cw = new ClassWriter(cr, needComputeMaxs(loader) ? COMPUTE_MAXS : COMPUTE_FRAMES) {
            @Override
            protected ClassLoader getClassLoader() {
                return loader;
            }
        };
        final ClassVisitor cv = new ProfilingClassAdapter(cw, className);
        cr.accept(cv, EXPAND_FRAMES);
        return cw.toByteArray();
    }
```

**Comment by LinShunKang** [comment]
> > > > > 这是跟其它的 agent 冲突了吧，我本地用 jdk20 起了一个 springboot2.7.8 的 demo 没问题
> > > > 
> > > > 
> > > > 不是
> > > 
> > > 
> > > 有复现的 demo 么，图里也看不出啥来，或者加载的那个类有啥特别的
> > 
> > 
> > 从代码上看没什么特别的：
> > 
> > * `class A extends B`
> > * 在加载 B 时抛出 `java.lang.ClassCircularityError: A`
> 
> 那说明 B extends A ? 要么类库出现了多个版本了
 
B 不会继承 A 否则编译都通不过；还是类加载的问题

**Comment by LinShunKang** [comment]
@JiaRG 
如果以这个为 v0.1:
```
    private byte[] getBytes(final ClassLoader loader,
                            String className,
                            byte[] classFileBuffer) {
        final ClassReader cr = new ClassReader(classFileBuffer);
        final ClassWriter cw = new ClassWriter(cr, needComputeMaxs(loader) ? COMPUTE_MAXS : COMPUTE_FRAMES) {
            @Override
            protected ClassLoader getClassLoader() {
                return loader;
            }
        };
        final ClassVisitor cv = new ProfilingClassAdapter(cw, className);
        cr.accept(cv, EXPAND_FRAMES);
        return cw.toByteArray();
    }
```

以这个为 v1:
```
    private byte[] getBytes(ClassLoader loader,
                            String className,
                            byte[] classFileBuffer) {
        ClassReader cr = new ClassReader(classFileBuffer);
        ClassWriter cw = new ClassWriter(cr, ClassWriter.COMPUTE_FRAMES) {
            @Override
            protected ClassLoader getClassLoader() {
                return Thread.currentThread().getContextClassLoader();
            }
        };
        ClassVisitor cv = new ProfilingClassAdapter(cw, className);
        cr.accept(cv, ClassReader.SKIP_FRAMES);
        return cw.toByteArray();
    }
```

那么，在没有 MyPerf4J 和 有 MyPerf4J v0.1 与 v1 的版本在添加了 -XX:+TraceClassLoading 参数后的日志（做了脱敏与过滤）为：
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/7189879/236679871-5d9980fe-7d7f-42b5-9773-65750f68525f.png">

你可以看到有问题的 v1 版本的类加载与另外两个明显不同

**Comment by LinShunKang** [comment]
> 你试试这个方案：
> 
> ```
>     private byte[] getBytes(final ClassLoader loader,
>                             String className,
>                             byte[] classFileBuffer) {
>         final ClassReader cr = new ClassReader(classFileBuffer);
>         final ClassWriter cw = new ClassWriter(cr, needComputeMaxs(loader) ? COMPUTE_MAXS : COMPUTE_FRAMES) {
>             @Override
>             protected ClassLoader getClassLoader() {
>                 return loader;
>             }
>         };
>         final ClassVisitor cv = new ProfilingClassAdapter(cw, className);
>         cr.accept(cv, EXPAND_FRAMES);
>         return cw.toByteArray();
>     }
> ```

@JiaRG 这个 v0.1 的版本，你试了么？
