### ISSUE TITLE
请问可否加入接口的耗时统计，统计系统每个接口性能测试中时间

### ISSUE THREAD

**Issue by cfy3133** [LinShunKang/MyPerf4J#92]
**你想要的功能和某一个问题相关？请详细描述它。**
清晰和简要的描述你所遇到的问题。

**描述你想要的解决方式**
清晰和简要描述你想要的解决方式。

**描述你所构想的解决方式**
清晰和简要描述你思考过的可行方式。

**其他相关内容**
在这里添加与该功能相关的其他上下文内容或者截图。

**Comment by LinShunKang** [comment]
没太理解你的意思，能否说得详细一些？

**Comment by cfy3133** [comment]
你好，就是类似于jmeter接口压力测试统计的数据：
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/805fbce5-c2db-41a4-8d29-db4aaecbca3b)

**Comment by LinShunKang** [comment]
还是没理解，你要什么数据？

**Comment by cfy3133** [comment]
你好，就是InfluxDB+Grafana+jmeter接口压力测试时候，得出的接口相应时间的数据
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/097890a7-fe72-4f36-b53d-70668c86bcca)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/960a7909-6a5d-4ea2-98bf-74cbcdcc14c4)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/56de96f6-ea58-46cc-bdc5-bbda206b3ea9)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/b9ad7bb9-9b49-4389-b08f-0cee12801cba)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/a73011c9-9eee-4fe5-8a2a-6dfa6e23b1cc)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/1c80420a-d2f4-4524-a311-a5d8845fc7d3)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/1be2a353-a528-4f74-90f0-cf492279e9e2)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/e2cdff49-3fe0-433a-948e-fc76e3f79b22)
![image](https://github.com/LinShunKang/MyPerf4J/assets/43978367/e56f1e9e-1b05-4258-b454-a70c4eaac9b2)

**Comment by LinShunKang** [comment]
MyPerf4J 不是已经有指定方法的 RPS 和 RT 的各项 TP 数据了吗？如果你要的是压测报告，那这不是 MyPerf4J 的范畴，而是压测工具的范畴

**Comment by cfy3133** [comment]
你好，明白，我的意思是，有些接口是录制回放的，因为有些接口不好做压测，依赖第三方平台，只能录制线上的数据回放，所以没办法用接口工具做数据的统计，如果可以加上这个功能，录制回放的接口数据就可以得到解决

**Comment by LinShunKang** [comment]
> 你好，明白，我的意思是，有些接口是录制回放的，因为有些接口不好做压测，依赖第三方平台，只能录制线上的数据回放，所以没办法用接口工具做数据的统计，如果可以加上这个功能，录制回放的接口数据就可以得到解决

你好，你可以从 InfluxDB 中把指标查询出来，然后就可以按你自己的需求做分析和展示了

**Comment by cfy3133** [comment]
好的
