### ISSUE TITLE
你好 请问SpringMVC的项目支持嘛

### ISSUE THREAD

**Issue by abielyiyi** [LinShunKang/MyPerf4J#97]
**问题描述**

请问SpringMVC的项目支持嘛

**运行环境**
* MyPerf4J 版本号
* JDK 版本号，JDK6
* 运行容器和框架，Tomcat
* 操作系统，Linux

**JVM启动参数** 
```
请把你的JVM启动参数完整的复制出来
```

**配置文件** 
```
请把你的配置文件内容完整的复制出来
```

**异常堆栈** 
```
请把程序的错误栈信息完整的复制出来
```

**Comment by LinShunKang** [comment]
支持，直接把 Controller 对应类的包路径配置到 ‘filter.packages.include’ 里即可

**Comment by abielyiyi** [comment]
谢谢
