### ISSUE TITLE
你好，请问可否把配置文件做成一个UI界面的操作，方便管理

### ISSUE THREAD

**Issue by cfy3133** [LinShunKang/MyPerf4J#98]
**你想要的功能和某一个问题相关？请详细描述它。**
不同项目每次都需要配置一个新的模板文件，不是很方便

**描述你想要的解决方式**
对于配置文件能够做成一个单独的UI界面来操作，方便管理不同的项目

**描述你所构想的解决方式**
希望能够通过界面选择不同的项目，来关联不同的配置文件

**其他相关内容**
![1693359502160](https://github.com/LinShunKang/MyPerf4J/assets/43978367/28b09562-06a1-4630-938d-196c88f193a8)

**Comment by LinShunKang** [comment]
你好，如果需要页面的话，就需要引入一个配置中心了，复杂度也就随之上升了

**Comment by cfy3133** [comment]
你好，好滴，明白了，谢谢作者回复

**Comment by LinShunKang** [comment]
客气
