### ISSUE TITLE
WIKI文档里面的http配置

### ISSUE THREAD

**Issue by jackBaozz** [LinShunKang/MyPerf4J#99]
**问题描述**

请问,这个http服务器是用来做什么的? 找了相关文档都没提到这个Http端口2048的作用. 公司对端口管的比较严,想了解清楚.谢谢

**配置文件** 
```
属性 | 类型 | 必填 | 默认值 | 说明
http.server.port | int | No | 2048,2000,2040 | 配置 Http 服务器端口号，格式为：首选端口,备选最小端口,备选最大端口
http.server.min_workers | int | No | 1 | 配置 Http 服务器的最小 work 线程数
http.server.max_workers | int | No | 2 | 配置 Http 服务器的最大 work 线程数
http.server.accept_count | int | No | 1024 | 配置 Http 服务器的最大排队请求数
```

![image](https://github.com/LinShunKang/MyPerf4J/assets/5772152/358e2c22-ba4e-4b35-8cbf-234b55eb1636)

**Comment by LinShunKang** [comment]
目前只是用于切换日志级别

**Comment by jackBaozz** [comment]
> 目前只是用于切换日志级别

1. 那是否可以不启用这个http的端口? 我想禁用这个端口的服务如何操作.
2. 这个端口2000左右一般管的很严, 我们能用得是8000往后, 应该是可以自定义的吧?
2. 如果要切换日志级别, 请问怎么切换呢? 请求过这个http://127.0.0.1:2048 , 什么都没返回. 是否有安全方面隐患呢这个切换日志级别的http接口.

**Comment by LinShunKang** [comment]
> > 目前只是用于切换日志级别
> 
> 1. 那是否可以不启用这个http的端口? 我想禁用这个端口的服务如何操作.
> 2. 这个端口2000左右一般管的很严, 我们能用得是8000往后, 应该是可以自定义的吧?
> 3. 如果要切换日志级别, 请问怎么切换呢? 请求过这个http://127.0.0.1:2048 , 什么都没返回. 是否有安全方面隐患呢这个切换日志级别的http接口.

1.目前不可以
2.可以
3.应该没有安全隐患，除非 JDK 的实现有问题
